
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbt_nyc_taxi_bigquery'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt_nyc_taxi_bigquery'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Variables
vars:
  max_tip_amount: 1200


on-run-start:
  - "{{ create_if_not_exists_audits_table() }}"
  - "{{ insert_audit('on_run_start') }}"
on-run-end:
  - "{{ insert_audit('on_run_end') }}"
  - "{{ dbt_artifacts.upload_results(results) }}"

models:
  +labels:
    created_by: dbt
  dbt_nyc_taxi_bigquery:
    # Config indicated by + and applies to all files under models/staging/
    staging:
      +pre-hook:
        - "{{ insert_audit('model_staging_start') }}"
      +post-hook:
        - "{{ insert_audit('model_staging_end') }}"
      +schema: staging
      +materialized: view

      nyctaxi:
        +materialized: table

  dbt_artifacts:
    +schema: dbt_artifacts

seeds:
  +labels:
    created_by: dbt
